[build]
functions="functions"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/submitForm/*"
  status = 200
  to = "/.netlify/functions/api/submitForm/:splat"